name: Paul Tosch
favicon: null
layout_spectrum: 0
typography_spectrum: 0.443072
title: Paul Tosch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8879389
  lightness: 0.06878464
  saturation: 0.467763
  rhythmicContrast: 0.7015743
purpose: []
