layout_spectrum: 0
typography_spectrum: 0.443072
color:
  saturation: 0.467763
  lightness: 0.06878464
  brandStrength: 0.8879389
  rhythmicContrast: 0.7015743
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Paul Tosch
